Microsoft Windows [Version 10.0.19045.4529]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\ReSkill\Python\fyyur

C:\ReSkill\Python\fyyur>pip3 install virtualenv
Collecting virtualenv
  Downloading virtualenv-20.26.2-py3-none-any.whl.metadata (4.4 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv)
  Downloading distlib-0.3.8-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting filelock<4,>=3.12.2 (from virtualenv)
  Downloading filelock-3.15.1-py3-none-any.whl.metadata (2.8 kB)
Collecting platformdirs<5,>=3.9.1 (from virtualenv)
  Downloading platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Downloading virtualenv-20.26.2-py3-none-any.whl (3.9 MB)
   ---------------------------------------- 3.9/3.9 MB 22.7 MB/s eta 0:00:00
Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
   ---------------------------------------- 468.9/468.9 kB 28.7 MB/s eta 0:00:00
Downloading filelock-3.15.1-py3-none-any.whl (15 kB)
Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.8 filelock-3.15.1 platformdirs-4.2.2 virtualenv-20.26.2

C:\ReSkill\Python\fyyur>node -v
v20.14.0

C:\ReSkill\Python\fyyur>npm -v
10.7.0

C:\ReSkill\Python\fyyur>git remote -v
Python  https://github.com/tharunkumars/Python.git (fetch)
Python  https://github.com/tharunkumars/Python.git (push)

C:\ReSkill\Python\fyyur>python -m virtualenv env
created virtual environment CPython3.12.4.final.0-64 in 10597ms
  creator CPython3Windows(dest=C:\ReSkill\Python\fyyur\env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=C:\Users\tharunkumars\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

C:\ReSkill\Python\fyyur>env\Scripts\activate

C:\ReSkill\Python\fyyur>()

(env) C:\ReSkill\Python\fyyur>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

(env) C:\ReSkill\Python\fyyur>cd starter_code

(env) C:\ReSkill\Python\fyyur\starter_code>pip install -r requirements.txt
Collecting babel==2.9.0 (from -r requirements.txt (line 1))
  Using cached Babel-2.9.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting python-dateutil==2.6.0 (from -r requirements.txt (line 2))
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting flask-moment==0.11.0 (from -r requirements.txt (line 3))
  Using cached Flask_Moment-0.11.0-py2.py3-none-any.whl.metadata (762 bytes)
Collecting flask-wtf==0.14.3 (from -r requirements.txt (line 4))
  Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting flask_sqlalchemy==2.4.4 (from -r requirements.txt (line 5))
  Using cached Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting pytz>=2015.7 (from babel==2.9.0->-r requirements.txt (line 1))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting six>=1.5 (from python-dateutil==2.6.0->-r requirements.txt (line 2))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting Flask (from flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting WTForms (from flask-wtf==0.14.3->-r requirements.txt (line 4))
  Using cached wtforms-3.1.2-py3-none-any.whl.metadata (5.3 kB)
Collecting itsdangerous (from flask-wtf==0.14.3->-r requirements.txt (line 4))
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting SQLAlchemy>=0.8.0 (from flask_sqlalchemy==2.4.4->-r requirements.txt (line 5))
  Using cached SQLAlchemy-2.0.30-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting Werkzeug>=3.0.0 (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached werkzeug-3.0.3-py3-none-any.whl.metadata (3.7 kB)
Collecting Jinja2>=3.1.2 (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting click>=8.1.3 (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Collecting typing-extensions>=4.6.0 (from SQLAlchemy>=0.8.0->flask_sqlalchemy==2.4.4->-r requirements.txt (line 5))
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy>=0.8.0->flask_sqlalchemy==2.4.4->-r requirements.txt (line 5))
  Using cached greenlet-3.0.3-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Collecting markupsafe (from WTForms->flask-wtf==0.14.3->-r requirements.txt (line 4))
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting colorama (from click>=8.1.3->Flask->flask-moment==0.11.0->-r requirements.txt (line 3))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Using cached Babel-2.9.0-py2.py3-none-any.whl (8.8 MB)
Using cached python_dateutil-2.6.0-py2.py3-none-any.whl (194 kB)
Using cached Flask_Moment-0.11.0-py2.py3-none-any.whl (4.3 kB)
Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Using cached Flask_SQLAlchemy-2.4.4-py2.py3-none-any.whl (17 kB)
Using cached flask-3.0.3-py3-none-any.whl (101 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached SQLAlchemy-2.0.30-cp312-cp312-win_amd64.whl (2.1 MB)
Using cached wtforms-3.1.2-py3-none-any.whl (145 kB)
Using cached blinker-1.8.2-py3-none-any.whl (9.5 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached greenlet-3.0.3-cp312-cp312-win_amd64.whl (293 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl (17 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached werkzeug-3.0.3-py3-none-any.whl (227 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: pytz, typing-extensions, six, markupsafe, itsdangerous, greenlet, colorama, blinker, babel, WTForms, Werkzeug, SQLAlchemy, python-dateutil, Jinja2, click, Flask, flask-wtf, flask_sqlalchemy, flask-moment
Successfully installed Flask-3.0.3 Jinja2-3.1.4 SQLAlchemy-2.0.30 WTForms-3.1.2 Werkzeug-3.0.3 babel-2.9.0 blinker-1.8.2 click-8.1.7 colorama-0.4.6 flask-moment-0.11.0 flask-wtf-0.14.3 flask_sqlalchemy-2.4.4 greenlet-3.0.3 itsdangerous-2.2.0 markupsafe-2.1.5 python-dateutil-2.6.0 pytz-2024.1 six-1.16.0 typing-extensions-4.12.2

(env) C:\ReSkill\Python\fyyur\starter_code>export FLASK_APP=myapp
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>cd\

(env) C:\>cd C:\ReSkill\Python\fyyur\

(env) C:\ReSkill\Python\fyyur>export FLASK_APP=myapp
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur>flask
Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  An application to load must be given with the '--app' option, 'FLASK_APP'
  environment variable, or with a 'wsgi.py' or 'app.py' file in the current
  directory.

Options:
  -e, --env-file FILE   Load environment variables from this file. python-
                        dotenv must be installed.
  -A, --app IMPORT      The Flask application or factory function to load, in
                        the form 'module:name'. Module can be a dotted import
                        or file path. Name is not required if it is 'app',
                        'application', 'create_app', or 'make_app', and can be
                        'name(args)' to pass arguments.
  --debug / --no-debug  Set debug mode.
  --version             Show the Flask version.
  --help                Show this message and exit.

Commands:
  routes  Show the routes for the app.
  run     Run a development server.
  shell   Run a shell in the app context.

(env) C:\ReSkill\Python\fyyur>  flask -e FLASK_APP="myapp" --debug run app.py
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: Invalid value for '-e' / '--env-file': File 'FLASK_APP=myapp' does not exist.

(env) C:\ReSkill\Python\fyyur>flask -e "FLASK_APP=myapp"
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: Invalid value for '-e' / '--env-file': File 'FLASK_APP=myapp' does not exist.

(env) C:\ReSkill\Python\fyyur>flask "FLASK_APP=myapp"
Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'FLASK_APP=myapp'.

(env) C:\ReSkill\Python\fyyur>flask FLASK_APP="myapp"
Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'FLASK_APP=myapp'.

(env) C:\ReSkill\Python\fyyur>flask --debug run app.py
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra argument (app.py)

(env) C:\ReSkill\Python\fyyur> flask run app.py --debug FLASK_APP="myapp"
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra arguments (app.py FLASK_APP=myapp)

(env) C:\ReSkill\Python\fyyur>flask run --help
Usage: flask run [OPTIONS]

  Run a local development server.

  This server is for development purposes only. It does not provide the
  stability, security, or performance of production WSGI servers.

  The reloader and debugger are enabled by default with the '--debug' option.

Options:
  --debug / --no-debug            Set debug mode.
  -h, --host TEXT                 The interface to bind to.
  -p, --port INTEGER              The port to bind to.
  --cert PATH                     Specify a certificate file to use HTTPS.
  --key FILE                      The key file to use when specifying a
                                  certificate.
  --reload / --no-reload          Enable or disable the reloader. By default
                                  the reloader is active if debug is enabled.
  --debugger / --no-debugger      Enable or disable the debugger. By default
                                  the debugger is active if debug is enabled.
  --with-threads / --without-threads
                                  Enable or disable multithreading.
  --extra-files PATH              Extra files that trigger a reload on change.
                                  Multiple paths are separated by ';'.
  --exclude-patterns PATH         Files matching these fnmatch patterns will
                                  not trigger a reload on change. Multiple
                                  patterns are separated by ';'.
  --help                          Show this message and exit.

(env) C:\ReSkill\Python\fyyur>flask run --debug app.py
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra argument (app.py)

(env) C:\ReSkill\Python\fyyur>flask run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not locate a Flask application. Use the 'flask --app' option, 'FLASK_APP' environment variable, or a 'wsgi.py' or 'app.py' file in the current directory.

(env) C:\ReSkill\Python\fyyur>cd starter_code

(env) C:\ReSkill\Python\fyyur\starter_code>export FLASK_APP=myapp
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>flask run --debug app.py
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra argument (app.py)

(env) C:\ReSkill\Python\fyyur\starter_code>flask run app.py --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra argument (app.py)

(env) C:\ReSkill\Python\fyyur\starter_code>export FLASK_APP=myapp
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>export FLASK_APP="myapp"
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>export "FLASK_APP=myapp"
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>set FLASK_APP=app.py

(env) C:\ReSkill\Python\fyyur\starter_code>flask run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 1, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'


(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
Installing collected packages: setuptools
Successfully installed setuptools-70.0.0

(env) C:\ReSkill\Python\fyyur\starter_code>flask run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils

(env) C:\ReSkill\Python\fyyur\starter_code>pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils

(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install --upgrade Flask
Requirement already satisfied: Flask in c:\reskill\python\fyyur\env\lib\site-packages (3.0.3)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask) (1.8.2)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=8.1.3->Flask) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Jinja2>=3.1.2->Flask) (2.1.5)

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>pip install --upgrade flask-moment
Requirement already satisfied: flask-moment in c:\reskill\python\fyyur\env\lib\site-packages (0.11.0)
Collecting flask-moment
  Downloading Flask_Moment-1.0.6-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: Flask in c:\reskill\python\fyyur\env\lib\site-packages (from flask-moment) (3.0.3)
Collecting packaging>=14.1 (from flask-moment)
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment) (1.8.2)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=8.1.3->Flask->flask-moment) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Jinja2>=3.1.2->Flask->flask-moment) (2.1.5)
Downloading Flask_Moment-1.0.6-py3-none-any.whl (6.2 kB)
Downloading packaging-24.1-py3-none-any.whl (53 kB)
   ---------------------------------------- 54.0/54.0 kB 280.4 kB/s eta 0:00:00
Installing collected packages: packaging, flask-moment
  Attempting uninstall: flask-moment
    Found existing installation: Flask-Moment 0.11.0
    Uninstalling Flask-Moment-0.11.0:
      Successfully uninstalled Flask-Moment-0.11.0
Successfully installed flask-moment-1.0.6 packaging-24.1

(env) C:\ReSkill\Python\fyyur\starter_code>pip install Werkzeug==2.0.0
Collecting Werkzeug==2.0.0
  Downloading Werkzeug-2.0.0-py3-none-any.whl.metadata (4.4 kB)
Downloading Werkzeug-2.0.0-py3-none-any.whl (288 kB)
   ---------------------------------------- 288.1/288.1 kB 3.6 MB/s eta 0:00:00
Installing collected packages: Werkzeug
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 3.0.3
    Uninstalling Werkzeug-3.0.3:
      Successfully uninstalled Werkzeug-3.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 3.0.3 requires Werkzeug>=3.0.0, but you have werkzeug 2.0.0 which is incompatible.
Successfully installed Werkzeug-2.0.0

(env) C:\ReSkill\Python\fyyur\starter_code>pip uninstall Flask
Found existing installation: Flask 3.0.3
Uninstalling Flask-3.0.3:
  Would remove:
    c:\reskill\python\fyyur\env\lib\site-packages\flask-3.0.3.dist-info\*
    c:\reskill\python\fyyur\env\lib\site-packages\flask\*
    c:\reskill\python\fyyur\env\scripts\flask.exe
Proceed (Y/n)? n

(env) C:\ReSkill\Python\fyyur\starter_code>flask run --debug
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ReSkill\Python\fyyur\env\Scripts\flask.exe\__main__.py", line 4, in <module>
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\__init__.py", line 5, in <module>
    from . import json as json
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\json\__init__.py", line 6, in <module>
    from ..globals import current_app
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\globals.py", line 25, in <module>
    app_ctx: AppContext = LocalProxy(  # type: ignore[assignment]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LocalProxy.__init__() got an unexpected keyword argument 'unbound_message'

(env) C:\ReSkill\Python\fyyur\starter_code>pip uninstall Flask
Found existing installation: Flask 3.0.3
Uninstalling Flask-3.0.3:
  Would remove:
    c:\reskill\python\fyyur\env\lib\site-packages\flask-3.0.3.dist-info\*
    c:\reskill\python\fyyur\env\lib\site-packages\flask\*
    c:\reskill\python\fyyur\env\scripts\flask.exe
Proceed (Y/n)? Y
  Successfully uninstalled Flask-3.0.3

(env) C:\ReSkill\Python\fyyur\starter_code>pip install flask==2.0.3
Collecting flask==2.0.3
  Downloading Flask-2.0.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: Werkzeug>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from flask==2.0.3) (2.0.0)
Requirement already satisfied: Jinja2>=3.0 in c:\reskill\python\fyyur\env\lib\site-packages (from flask==2.0.3) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from flask==2.0.3) (2.2.0)
Requirement already satisfied: click>=7.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from flask==2.0.3) (8.1.7)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=7.1.2->flask==2.0.3) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Jinja2>=3.0->flask==2.0.3) (2.1.5)
Downloading Flask-2.0.3-py3-none-any.whl (95 kB)
   ---------------------------------------- 95.6/95.6 kB 496.1 kB/s eta 0:00:00
Installing collected packages: flask
Successfully installed flask-2.0.3

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run --debug
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: No such option: --debug (Possible options: --debugger, --no-debugger)

(env) C:\ReSkill\Python\fyyur\starter_code>pip install -r requirements.txt
Requirement already satisfied: babel==2.9.0 in c:\reskill\python\fyyur\env\lib\site-packages (from -r requirements.txt (line 1)) (2.9.0)
Requirement already satisfied: python-dateutil==2.6.0 in c:\reskill\python\fyyur\env\lib\site-packages (from -r requirements.txt (line 2)) (2.6.0)
Collecting flask-moment==0.11.0 (from -r requirements.txt (line 3))
  Using cached Flask_Moment-0.11.0-py2.py3-none-any.whl.metadata (762 bytes)
Requirement already satisfied: flask-wtf==0.14.3 in c:\reskill\python\fyyur\env\lib\site-packages (from -r requirements.txt (line 4)) (0.14.3)
Requirement already satisfied: flask_sqlalchemy==2.4.4 in c:\reskill\python\fyyur\env\lib\site-packages (from -r requirements.txt (line 5)) (2.4.4)
Requirement already satisfied: pytz>=2015.7 in c:\reskill\python\fyyur\env\lib\site-packages (from babel==2.9.0->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: six>=1.5 in c:\reskill\python\fyyur\env\lib\site-packages (from python-dateutil==2.6.0->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: Flask in c:\reskill\python\fyyur\env\lib\site-packages (from flask-moment==0.11.0->-r requirements.txt (line 3)) (2.0.3)
Requirement already satisfied: WTForms in c:\reskill\python\fyyur\env\lib\site-packages (from flask-wtf==0.14.3->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: itsdangerous in c:\reskill\python\fyyur\env\lib\site-packages (from flask-wtf==0.14.3->-r requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: SQLAlchemy>=0.8.0 in c:\reskill\python\fyyur\env\lib\site-packages (from flask_sqlalchemy==2.4.4->-r requirements.txt (line 5)) (2.0.30)
Requirement already satisfied: Werkzeug>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: Jinja2>=3.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3)) (3.1.4)
Requirement already satisfied: click>=7.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask-moment==0.11.0->-r requirements.txt (line 3)) (8.1.7)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\reskill\python\fyyur\env\lib\site-packages (from SQLAlchemy>=0.8.0->flask_sqlalchemy==2.4.4->-r requirements.txt (line 5)) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\reskill\python\fyyur\env\lib\site-packages (from SQLAlchemy>=0.8.0->flask_sqlalchemy==2.4.4->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: markupsafe in c:\reskill\python\fyyur\env\lib\site-packages (from WTForms->flask-wtf==0.14.3->-r requirements.txt (line 4)) (2.1.5)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=7.1.2->Flask->flask-moment==0.11.0->-r requirements.txt (line 3)) (0.4.6)
Using cached Flask_Moment-0.11.0-py2.py3-none-any.whl (4.3 kB)
Installing collected packages: flask-moment
  Attempting uninstall: flask-moment
    Found existing installation: Flask-Moment 1.0.6
    Uninstalling Flask-Moment-1.0.6:
      Successfully uninstalled Flask-Moment-1.0.6
Successfully installed flask-moment-0.11.0

(env) C:\ReSkill\Python\fyyur\starter_code>export FLASK_APP=myapp
'export' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>set FLASK_APP=app

(env) C:\ReSkill\Python\fyyur\starter_code>set FLASK_ENV=development

(env) C:\ReSkill\Python\fyyur\starter_code>python3 app.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

(env) C:\ReSkill\Python\fyyur\starter_code>flask run app.py
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Got unexpected extra argument (app.py)

(env) C:\ReSkill\Python\fyyur\starter_code>flask --help
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  Provides commands from Flask, extensions, and the application. Loads the
  application defined in the FLASK_APP environment variable, or from a wsgi.py
  file. Setting the FLASK_ENV environment variable to 'development' will
  enable debug mode.

    > set FLASK_APP=hello.py
    > set FLASK_ENV=development
    > flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  routes  Show the routes for the app.
  run     Run a development server.
  shell   Run a shell in the app context.

(env) C:\ReSkill\Python\fyyur\starter_code>set FLASK_APP=app.py

(env) C:\ReSkill\Python\fyyur\starter_code>set FLASK_ENV=development

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import Moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 14, in <module>
    from flask_wtf import Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>Form
'Form' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>pip install Jinja2
Requirement already satisfied: Jinja2 in c:\reskill\python\fyyur\env\lib\site-packages (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Jinja2) (2.1.5)

(env) C:\ReSkill\Python\fyyur\starter_code>
(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    import flask_moment
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 9, in <module>
    from flask_moment import *
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_moment.py", line 3, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 14, in <module>
    from flask_wtf import *
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 15, in <module>
    from forms import *
  File "C:\ReSkill\Python\fyyur\starter_code\forms.py", line 2, in <module>
    from flask_wtf import Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install flask_wtf
Requirement already satisfied: flask_wtf in c:\reskill\python\fyyur\env\lib\site-packages (0.14.3)
Requirement already satisfied: Flask in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (2.0.3)
Requirement already satisfied: WTForms in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (3.1.2)
Requirement already satisfied: itsdangerous in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (2.2.0)
Requirement already satisfied: Werkzeug>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (2.0.0)
Requirement already satisfied: Jinja2>=3.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (3.1.4)
Requirement already satisfied: click>=7.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (8.1.7)
Requirement already satisfied: markupsafe in c:\reskill\python\fyyur\env\lib\site-packages (from WTForms->flask_wtf) (2.1.5)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=7.1.2->Flask->flask_wtf) (0.4.6)

(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install wtforms
Requirement already satisfied: wtforms in c:\reskill\python\fyyur\env\lib\site-packages (3.1.2)
Requirement already satisfied: markupsafe in c:\reskill\python\fyyur\env\lib\site-packages (from wtforms) (2.1.5)

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 10, in <module>
    from jinja2.utils import Markup
ImportError: cannot import name 'Markup' from 'jinja2.utils' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\utils.py)


(env) C:\ReSkill\Python\fyyur\starter_code>pip3 install jinja2
Requirement already satisfied: jinja2 in c:\reskill\python\fyyur\env\lib\site-packages (3.1.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from jinja2) (2.1.5)

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 15, in <module>
    from forms import *
  File "C:\ReSkill\Python\fyyur\starter_code\forms.py", line 2, in <module>
    from flask_wtf import Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 14, in <module>
    from flask_wtf import *
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 15, in <module>
    from forms import *
  File "C:\ReSkill\Python\fyyur\starter_code\forms.py", line 2, in <module>
    from flask_wtf import FlaskForm
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>pip install forms
ERROR: Could not find a version that satisfies the requirement forms (from versions: none)
ERROR: No matching distribution found for forms

(env) C:\ReSkill\Python\fyyur\starter_code>pip install flask_wtf
Requirement already satisfied: flask_wtf in c:\reskill\python\fyyur\env\lib\site-packages (0.14.3)
Requirement already satisfied: Flask in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (2.0.3)
Requirement already satisfied: WTForms in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (3.1.2)
Requirement already satisfied: itsdangerous in c:\reskill\python\fyyur\env\lib\site-packages (from flask_wtf) (2.2.0)
Requirement already satisfied: Werkzeug>=2.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (2.0.0)
Requirement already satisfied: Jinja2>=3.0 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (3.1.4)
Requirement already satisfied: click>=7.1.2 in c:\reskill\python\fyyur\env\lib\site-packages (from Flask->flask_wtf) (8.1.7)
Requirement already satisfied: markupsafe in c:\reskill\python\fyyur\env\lib\site-packages (from WTForms->flask_wtf) (2.1.5)
Requirement already satisfied: colorama in c:\reskill\python\fyyur\env\lib\site-packages (from click>=7.1.2->Flask->flask_wtf) (0.4.6)

(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 15, in <module>
    from forms import *
  File "C:\ReSkill\Python\fyyur\starter_code\forms.py", line 2, in <module>
    from flask_wtf import Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\__init__.py", line 4, in <module>
    from .form import FlaskForm, Form
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_wtf\form.py", line 4, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (C:\ReSkill\Python\fyyur\env\Lib\site-packages\jinja2\__init__.py)


(env) C:\ReSkill\Python\fyyur\starter_code>  flask run
 * Serving Flask app 'app.py' (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ReSkill\Python\fyyur\env\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 995, in main
    cli.main(args=sys.argv[1:])
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 601, in main
    return super().main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 850, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 325, in __init__
    self._load_unlocked()
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 351, in _load_unlocked
    self._app = rv = self.loader()
                     ^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 407, in load_app
    app = locate_app(self, import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask\cli.py", line 260, in locate_app
    __import__(module_name)
  File "C:\ReSkill\Python\fyyur\starter_code\app.py", line 23, in <module>
    db = SQLAlchemy(app)
         ^^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_sqlalchemy\__init__.py", line 719, in __init__
    _include_sqlalchemy(self, query_class)
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\flask_sqlalchemy\__init__.py", line 74, in _include_sqlalchemy
    for key in module.__all__:
               ^^^^^^^^^^^^^^
  File "C:\ReSkill\Python\fyyur\env\Lib\site-packages\sqlalchemy\__init__.py", line 294, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

(env) C:\ReSkill\Python\fyyur\starter_code>python -V
Python 3.12.4

(env) C:\ReSkill\Python\fyyur\starter_code>pyenv versions
'pyenv' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\ReSkill\Python\fyyur\starter_code>cd\

(env) C:\>pyenv
'pyenv' is not recognized as an internal or external command,
operable program or batch file.

(env) C:\>